plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
nodeLinker: "pnp"   
pnpMode: "loose"
packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
