FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./
COPY yarn.lock ./
COPY .yarnrc.yml ./
COPY tsconfig.json ./
COPY ./packages/server/package.json packages/server/
COPY ./.yarn/plugins .yarn/plugins
COPY ./.yarn/sdks .yarn/sdks
COPY ./.yarn/releases .yarn/releases

# install yarn 3
RUN corepack enable
RUN yarn set version 3.5.1

RUN yarn install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY ./packages/server packages/server

COPY ./packages/server/.env.production packages/server/.env
COPY ./packages/server/.env.example.production packages/server/.env.example

# Compile typescript files
RUN yarn workspace server build

ENV NODE_ENV production

EXPOSE 8080
CMD ["yarn", "workspace", "server", "start"]
USER node



